// Custom Map
#include "custom\Maps\High End Trader AAC-Flugfeld Objekts.sqf"
#include "custom\Maps\High End Trader Molos Objekts.sqf"
#include "custom\Maps\High End Trader USS-Freedom Objekts.sqf"
#include "custom\Maps\Military Delfinaki.sqf"
#include "custom\Maps\Military Feres.sqf"
#include "custom\Maps\Military Kavala.sqf"
#include "custom\Maps\Military Sofia.sqf"
#include "custom\Maps\Military Thronos.sqf"
#include "custom\Maps\Military Vikos.sqf"
#include "custom\Maps\Safezone Airfield Objekts.sqf"
#include "custom\Maps\Safezone Kavala Objekts.sqf"
#include "custom\Maps\Safezone Sideras Objekts.sqf"
#include "custom\Maps\Drug_Concret_Buildings.sqf"
#include "custom\Maps\Safezone BW Objekts.sqf"
